# Generated by Django 3.2.7 on 2021-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название тренировки', max_length=255)),
                ('content', models.TextField(help_text='Описание тренировки')),
                ('type', models.CharField(blank=True, choices=[('po', 'Силовая'), ('fu', 'Функциональная'), ('ca', 'Кардион'), ('cr', 'Кросфит'), ('pi', 'Пилатес'), ('re', 'Реабилитационная')], default='po', help_text='Выбери вид тренировки', max_length=2)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
